# Generated by Django 3.1.5 on 2021-07-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='invoiceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceNumber', models.EmailField(max_length=254)),
                ('clientEmail', models.EmailField(max_length=254)),
                ('clientName', models.CharField(max_length=50)),
                ('projectName', models.CharField(max_length=50)),
                ('amout', models.BigIntegerField()),
            ],
            options={
                'db_table': 'invoiceData',
            },
        ),
    ]
