# Generated by Django 3.1.5 on 2021-07-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedata',
            name='paymentStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoicedata',
            name='invoiceNumber',
            field=models.CharField(max_length=50),
        ),
    ]
