# Generated by Django 3.1.5 on 2021-07-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0002_auto_20210728_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicedata',
            name='paymentStatus',
        ),
        migrations.AddField(
            model_name='invoicedata',
            name='paymentlink',
            field=models.CharField(default='', max_length=200),
        ),
    ]
