# Generated by Django 3.1.5 on 2021-07-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0003_auto_20210728_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedata',
            name='paymentlink',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
