# Generated by Django 3.2.5 on 2021-07-31 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0004_auto_20210728_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedata',
            name='paymentstatus',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='invoicedata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
